# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Liu xiya
tagline:          ''
description:      'cool girls know how to code'
url:              http://doulemint.github.io/
baseurl:          /

version:          1.0

github:
  repo:           https://github.com/doulemint/doulemint.github.io

plugins:          [jekyll-paginate]

port: 4001
