# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty


# Setup
title:            Liu xiya
tagline:          'A Jekyll theme'
description:      ''
url:              http://
baseurl:          /

author:
  name:
  url:

paginate:         5

# Custom vars
version:

github:
  repo:
