# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Liu xiya
tagline:          ''
description:      ''
url:              http://doulemint.github.io/
baseurl:          /

author:
  name:
  url:

paginate:         5

# Custom vars
version:

github:
  repo:
